[package]
name = "rtic-zero-cortex-m"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mutex = { path = "../../mutex" }
rtic-zero = { path = "../../" }

cortex-m-semihosting = "0.3.3"
